### ISSUE TITLE
Are there any materials explaining the code and data ? 

### ISSUE THREAD

**Issue by JiweiTian** [mrinmoysarkar/UAV-STATE-Estimation#1]
Are there any materials explaining the code and data ? 

Thank you very much.

**Comment by mrinmoysarkar** [comment]
please read the following paper: https://link.springer.com/article/10.1007/s10846-019-01078-y
also a preprint version is available here: https://www.researchgate.net/profile/Mrinmoy_Sarkar3/publication/335610461_PIE_a_Tool_for_Data-Driven_Autonomous_UAV_Flight_Testing/links/5d8bb3fc458515202b68f081/PIE-a-Tool-for-Data-Driven-Autonomous-UAV-Flight-Testing.pdf

**Comment by JiweiTian** [comment]
Thank you very much.
